version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: homestead
      POSTGRES_USER: homestead
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data/:/var/lib/postgresql/data
  postgres-test:
    image: postgres
    environment:
      POSTGRES_DB: homestead
      POSTGRES_USER: homestead
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
  # redis:
  #   image: redis:alpine
  #   ports:
  #     - 6379:6379